name: Build & Test  

on: [push] 

jobs: 

  build: 

    runs-on: ubuntu-latest 

    steps: 

    - uses: actions/checkout@v4 

    - name: Setup .NET 

      uses: actions/setup-dotnet@v4 

      with: 

        dotnet-version: 8.0 

    - name: Restore workloads 

      run: dotnet workload restore ./Pipeline/Pipeline/Pipeline.csproj 

    - name: Restore dependencies 

      run: dotnet restore ./Pipeline/Pipeline/Pipeline.csproj 

    - name: Build 

      run: dotnet build ./Pipeline/Pipeline/Pipeline.csproj --no-restore --framework net8.0 

    - name: Test 

      run: dotnet test ./Pipeline/Pipeline/Pipeline.csproj --framework net8.0 